name: AUTO_TASK_FOR_BILIBILI

on:
  push:
    branches: main
  workflow_dispatch:
  schedule:
    - cron: '30 21 * * *'

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 打印 Secrets 变量（仅验证是否存在，值会被脱敏）
        env:
          BILI_JCT: ${{ secrets.BILI_JCT }}
          DEDEUSERID: ${{ secrets.DEDEUSERID }}
          SESSDATA: ${{ secrets.SESSDATA }}
        run: |
          echo "BILI_JCT 的长度: ${#BILI_JCT}"  # 打印变量长度，验证是否有值
          echo "DEDEUSERID 的值: $DEDEUSERID"    # 实际显示为 ***
          echo "SESSDATA 的值: $SESSDATA"        # 实际显示为 ***
      
      # 后续步骤保持不变...
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      # ...（省略其他步骤）
